/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/generate-assets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/approvedComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/evaluateComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/rejectionComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/talepAdd`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/talepDetails`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/generate-assets`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/Talep/approvedComplaint`; params?: Router.UnknownOutputParams; } | { pathname: `/Talep/evaluateComplaint`; params?: Router.UnknownOutputParams; } | { pathname: `/Talep/rejectionComplaint`; params?: Router.UnknownOutputParams; } | { pathname: `/Talep/talepAdd`; params?: Router.UnknownOutputParams; } | { pathname: `/Talep/talepDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/generate-assets${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `/Talep/approvedComplaint${`?${string}` | `#${string}` | ''}` | `/Talep/evaluateComplaint${`?${string}` | `#${string}` | ''}` | `/Talep/rejectionComplaint${`?${string}` | `#${string}` | ''}` | `/Talep/talepAdd${`?${string}` | `#${string}` | ''}` | `/Talep/talepDetails${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/generate-assets`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/approvedComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/evaluateComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/rejectionComplaint`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/talepAdd`; params?: Router.UnknownInputParams; } | { pathname: `/Talep/talepDetails`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
